import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "../../../packages/components/public/style/styles.css";
import "../../../packages/components/src/atoms/Menu/SliderSelector/slide_selector.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          antialiased
          bg-[#FFFCF7] 
        `}
      >
        {children}
      </body>
    </html>
  );
}
