server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: match-me-chat
  datasource:
    url: jdbc:postgresql://postgres_container:5432/chat
    username: chat
    password: chat
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    tech.kood.match_me.chatspace: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics

# Optional: WebSocket or other chat-specific configs
chatspace:
  websocket:
    endpoint: /ws
    allowed-origins: "*"