user-management:
  jwt:
    secret: q+6sNpZcOymRrX2U6o4aU2jCLvQhVkODoUwiyQ6QL/I=
    expiration: 3600
    issuer: match-me
  refresh-token:
    expiration: 604800
    clean-up-interval: 20
  user:
    password:
      min-length: 8
      max-length: 60
      require-uppercase: true
      require-special: true

logging:
  level:
    root: INFO
    tech.kood.match_me.user_management: DEBUG
    org.springframework.jms: DEBUG
    org.apache.activemq: DEBUG
    org.springframework.boot.autoconfigure.jms: DEBUG

hawtio:
  authenticationEnabled: false

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        hawtio : hawtio/console
      exposure:
        include:
        - hawtio
        - jolokia

spring:
  jmx:
    enabled: true
  jms: 
    cache:
      session-cache-size: 5
  artemis:
    mode: embedded
    password: match-me
    user: match-me
    embedded:
      enabled: true
      persistent: false
  datasource:
    user-management:
      jdbc-url: jdbc:postgresql://localhost:5432/user_management
      username: user_management
      password: user_management
      driver-class-name: org.postgresql.Driver
    connections:
      jdbc-url: jdbc:postgresql://localhost:5432/connections
      username: connections
      password: connections
      driver-class-name: org.postgresql.Driver
  application:
    name: match-me
  flyway:
    enabled: false
testcontainers:
  reuse:
    enabled: true