user-management:
  jwt:
    secret: q+6sNpZcOymRrX2U6o4aU2jCLvQhVkODoUwiyQ6QL/I=
    expiration: 3600
    issuer: match-me
  refresh-token:
    expiration: 604800
    clean-up-interval: 20

logging:
  level:
    root: INFO
    tech.kood.match_me.user_management: DEBUG

spring:
  datasource:
    user-management:
      jdbc-url: jdbc:postgresql://localhost:5432/user_management
      username: user_management
      password: user_management
      driver-class-name: org.postgresql.Driver
  application:
    name: match-me
  flyway:
    enabled: false

testcontainers:
  reuse:
    enabled: true