spring:
  datasource:
    user-management:
      url: jdbc:postgres://localhost:5432/user_management
      username: user_management
      password: user_management
      driver-class-name: org.postgresql.Driver
  application:
    name: match-me
  flyway:
    enabled: false