user-management:
  jwt:
    secret: your_jwt_secret
    expiration: 3600
  refresh-token:
    expiration: 604800

spring:
  datasource:
    user-management:
      jdbc-url: jdbc:postgresql://localhost:5432/user_management
      username: user_management
      password: user_management
      driver-class-name: org.postgresql.Driver
  application:
    name: match-me
  flyway:
    enabled: false