spring:
  datasource:
    user-management:
      jdbc-url: jdbc:postgresql://postgres_container:5432/matching
      username: matching
      password: matching
      driver-class-name: org.postgresql.Driver
  application:
    name: match-me
  flyway:
    enabled: false

testcontainers:
  reuse:
    enabled: false

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.engine.jdbc.env.internal: DEBUG
    org.hibernate.engine.jdbc.connections.internal: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG