server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: match-me-chat
  datasource:
    chatspace:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/chat
      username: chat
      password: chat
      driver-class-name: org.postgresql.Driver
    profile:
      jdbc-url: jdbc:postgresql://localhost:5432/profile
      username: profile
      password: profile
      driver-class-name: org.postgresql.Driver
    user-management:
      jdbc-url: jdbc:postgresql://postgres_container:5432/matching
      username: matching
      password: matching
      driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
  flyway:
    enabled: false
  hawtio:
    authenticationEnabled: false
    
user-management:
  jwt:
    secret: q+6sNpZcOymRrX2U6o4aU2jCLvQhVkODoUwiyQ6QL/I=
    expiration: 3600
    issuer: match-me
  refresh-token:
    expiration: 604800
    clean-up-interval: 20
  user:
    password:
      min-length: 8
      max-length: 60
      require-uppercase: true
      require-special: true

logging:
  level:
    root: INFO
    tech.kood.match_me.chatspace: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


# Optional: WebSocket or other chat-specific configs
chatspace:
  websocket:
    endpoint: /ws
    allowed-origins: "*"