server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: match-me

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    matching:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/matching
      username: matching
      password: matching
      driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: update
        properties:
          hibernate:
            ddl-auto: update
    chatspace:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/chat
      username: chat
      password: chat
      driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: update
        properties:
          hibernate:
            ddl-auto: update
    profile:
      jdbc-url: jdbc:postgresql://localhost:5432/profile
      username: profile
      password: profile
      driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: update
        properties:
          hibernate:
            ddl-auto: update
    user-management:
      jdbc-url: jdbc:postgresql://localhost:5432/user_management
      username: user_management
      password: user_management
      driver-class-name: org.postgresql.Driver
    connections:
      jdbc-url: jdbc:postgresql://localhost:5432/connections
      username: connections
      password: connections
      driver-class-name: org.postgresql.Driver
      
  flyway:
    enabled: false
  hawtio:
    authenticationEnabled: false

# MOVE THIS OUT - Same level as 'spring:', NOT under 'datasource:'
app:
  upload:
    dir: ${user.home}/profile-images
    
user-management:
  jwt:
    secret: q+6sNpZcOymRrX2U6o4aU2jCLvQhVkODoUwiyQ6QL/I=
    expiration: 3600
    issuer: match-me
  refresh-token:
    expiration: 604800
    clean-up-interval: 20
  user:
    password:
      min-length: 8
      max-length: 60
      require-uppercase: true
      require-special: true

logging:
  level:
    root: INFO
    tech.kood.match_me.chatspace: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

chatspace:
  websocket:
    endpoint: /ws
    allowed-origins: "*"