spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/match_me_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  application:
    name: match-me

  flyway:
    enabled: false