spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/match_me_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    locations: classpath:/profile/database/flyway
    url: jdbc:postgresql://postgres_container:5432/match_me_db
    user: admin
    password: admin
