spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/match_me_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:profile/database/flyway
