version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: match_me_db
    ports:
      - "5432:5432"
    volumes:
      -  postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts/init-user-management.sql:/docker-entrypoint-initdb.d/init-user-management.sql
      - ./postgres/scripts/init-chat.sql:/docker-entrypoint-initdb.d/init-chat.sql
      - ./postgres/scripts/init-connections.sql:/docker-entrypoint-initdb.d/init-connections.sql
      - ./postgres/scripts/init-matching.sql:/docker-entrypoint-initdb.d/init-matching.sql
      - ./postgres/scripts/init-profile.sql:/docker-entrypoint-initdb.d/init-profile.sql
#networks:
#  default:
#    external:
#      name: matchme-shared-net


volumes:
  postgres_data: