---
services:
  devcontainer:
    container_name: Match-me
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: $HOST_UID
        USER_GID: $HOST_GID
        USERNAME: $HOST_USERNAME 
        DOCKER_GID: $HOST_DOCKER_GID
    pull_policy: always
    env_file:
      - ../.env
    command: sleep infinity
    ports:
      - "8080:8080"
    volumes:
      - ../..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  default:
    name: matchme-shared-net
    external: true